### ISSUE TITLE
Publish event message with TTL metadata `key` is invalid

### ISSUE THREAD

**Issue by li1234yun** [dapr/python-sdk#317] opened 2021-12-21 04:03 UTC
## Expected Behavior

No exception.

## Actual Behavior

Raise ValueError Exception:

```
  File "/home/tzxd/code/crontab_celery/test/dapr_publish_test.py", line 14, in <module>
    r = c.publish_event(
  File "/home/tzxd/code/crontab_celery/.venv/lib/python3.9/site-packages/dapr/clients/grpc/client.py", line 350, in publish_event
    _, call = self._stub.PublishEvent.with_call(req, metadata=metadata)
  File "/home/tzxd/code/crontab_celery/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 955, in with_call
    state, call, = self._blocking(request, timeout, metadata, credentials,
  File "/home/tzxd/code/crontab_celery/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 926, in _blocking
    call = self._channel.segregated_call(
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 498, in grpc._cython.cygrpc.Channel.segregated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 366, in grpc._cython.cygrpc._segregated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 360, in grpc._cython.cygrpc._segregated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 218, in grpc._cython.cygrpc._call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 253, in grpc._cython.cygrpc._call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 61, in grpc._cython.cygrpc._raise_call_error
ValueError: metadata was invalid: ('ttlInSeconds', '120')
```

## Steps to Reproduce the Problem

```python3
import json
import unittest

from dapr.clients import DaprClient

# class PublishTest(unittest.TestCase):
#     def setUp(self) -> None:
#         pass

#     def test_publish(self):

with DaprClient() as c:
    try:
        r = c.publish_event(
            pubsub_name='pubsub',
            topic_name='topic',
            data=json.dumps({'a': 1, 'b': 2}),
            metadata=(('ttlInSeconds', '120'),),
            data_content_type=None,
        )
    except Exception as e:
        raise e

```

## Note

*GRPC metadata keys must be lowcase.*

grpc/grpc#9863

## Doc bug

[Python ttl sample metadata key has upperCase](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-message-ttl/#example)

**Comment by geekgao** [comment] 2021-12-31 02:40
In my case:

```
== APP ==   File "/home/alex/workplace/py39/lib/python3.9/site-packages/grpc/_channel.py", line 926, in _blocking
== APP ==     call = self._channel.segregated_call(
== APP ==            │    │        └ <method 'segregated_call' of 'grpc._cython.cygrpc.Channel' objects>
== APP ==            │    └ <grpc._cython.cygrpc.Channel object at 0x7fc9ae18ffa0>
== APP ==            └ <grpc._channel._UnaryUnaryMultiCallable object at 0x7fc9ae18f610>
== APP ==   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 498, in grpc._cython.cygrpc.Channel.segregated_call
== APP ==   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 366, in grpc._cython.cygrpc._segregated_call
== APP ==   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 360, in grpc._cython.cygrpc._segregated_call
== APP ==   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 218, in grpc._cython.cygrpc._call
== APP ==   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 246, in grpc._cython.cygrpc._call
== APP ==   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 89, in grpc._cython.cygrpc._operate
== APP ==   File "src/python/grpcio/grpc/_cython/_cygrpc/tag.pyx.pxi", line 64, in grpc._cython.cygrpc._BatchOperationTag.prepare
== APP ==   File "src/python/grpcio/grpc/_cython/_cygrpc/operation.pyx.pxi", line 37, in grpc._cython.cygrpc.SendInitialMetadataOperation.c
== APP ==   File "src/python/grpcio/grpc/_cython/_cygrpc/metadata.pyx.pxi", line 41, in grpc._cython.cygrpc._store_c_metadata
== APP ==
== APP == ValueError: too many values to unpack (expected 2)

```

**Comment by wcs1only** [comment] 2022-01-03 20:21
This appears to be a dupe of: #299

Metadata is an overloaded term between grpc metadata and dapr metadata in the python-sdk, unfortunately. 
Use the publish_metadata field in v1.4.1. We had the exact same problem with `rawPayload`, it just looks like we missed updating the `ttlInSeconds` documentation. Docs PR for `ttlInSeconds`:
https://github.com/dapr/docs/pull/2072

In the mean time, refer to the python-sdk example here for the correct usage: https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-raw/#publishing-raw-messages

**Closed** 2022-01-13 23:44 UTC
Labels: kind/bug
