### ISSUE TITLE
Missing dapr Python version 1.12.0 packages in PIP

### ISSUE THREAD

**Issue by synthetaic-cmccabe** [dapr/python-sdk#622] opened 2023-10-24 16:53 UTC
It appears that no dapr python api packages were deployed to PIP as part of the version 1.12.0 release.  Would it be possible to publish new package versions for the following dapr libraries?

https://pypi.org/project/dapr/
https://pypi.org/project/dapr-ext-grpc/
https://pypi.org/project/flask-dapr/
https://pypi.org/project/dapr-ext-fastapi/

**Comment by berndverst** [comment] 2023-10-31 21:11
Yes this is as expected, please see https://github.com/dapr/python-sdk/issues/608

There were missing dependency builds for Python 3.12 at release time.

**Comment by berndverst** [comment] 2023-10-31 21:11
Closing as duplicate of tracking issue.

**Closed by berndverst** 2023-10-31 21:11 UTC
