### ISSUE TITLE
Exception from Actor's method is not surfaced to the caller

### ISSUE THREAD

**Issue by amulyavarote** [dapr/python-sdk#452] opened 2022-09-06 23:53 UTC
## Describe the proposal

#Expected Behavior

Exception's error message (not stacktrace) from Actor's method is surfaced to the caller.
Add details like exception method, line number, exception type and generate an UUID to match the exceptions both on callee as well as caller side.

**Comment by amulyavarote** [comment] 2022-09-13 16:00
Example of exception details:
Dapr.Actors.ActorMethodInvocationException: Remote Actor Method Exception, DETAILS: Exception: NotImplementedException, Method Name: ExceptionExample, Line Number: 14, Exception uuid: d291a006-84d5-42c4-b39e-d6300e9ac38b

**Comment by berndverst** [comment] 2022-09-20 00:08
@amulyavarote more information is needed. Steps to reproduce, API method that is returning an error with insufficient information etc.

Right now this issue is not actionable.

**Comment by berndverst** [comment] 2022-09-26 19:31
@amulyavarote since I haven't received more info from you and this issue isn't actionable I will close it for now.

**Closed by berndverst** 2022-09-26 19:31 UTC
Labels: question

**Comment by amulyavarote** [comment] 2022-09-26 21:25
Steps to reproduce this error. 
1. Go to the file and line where the actor method is called.
2. And modify actor method to throw "NotImplementedError" to simulate method not implemented exception. 
```raise NotImplementedError("Method not implemented exception")``` 
You should see the below trace.

Existing behavior if the "NotImplementedError" exception is thrown. 

```== APP == call actor method via proxy.invoke_method()
== APP == Traceback (most recent call last):
== APP ==   File "/Users/amulyavarote/Documents/Project/python-sdk/examples/demo_actor/demo_actor/demo_actor_client.py", line 71, in <module>
== APP ==     asyncio.run(main())
== APP ==   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
== APP ==     return loop.run_until_complete(main)
== APP ==   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
== APP ==     return future.result()
== APP ==   File "/Users/amulyavarote/Documents/Project/python-sdk/examples/demo_actor/demo_actor/demo_actor_client.py", line 28, in main
== APP ==     rtn_bytes = await proxy.invoke_method("GetMyData")
== APP ==   File "/Users/amulyavarote/Documents/Project/python-sdk/dapr/actor/client/proxy.py", line 162, in invoke_method
== APP ==     return await self._dapr_client.invoke_method(
== APP ==   File "/Users/amulyavarote/Documents/Project/python-sdk/dapr/clients/http/dapr_actor_http_client.py", line 66, in invoke_method
== APP ==     body, _ = await self._client.send_bytes(method='POST', url=url, data=data, headers=headers)
== APP ==   File "/Users/amulyavarote/Documents/Project/python-sdk/dapr/clients/http/client.py", line 83, in send_bytes
== APP ==     raise (await self.convert_to_error(r))
== APP == dapr.clients.exceptions.DaprInternalError: ('error invoke actor method: rpc error: code = Internal desc = error invoke actor method: error from actor service: {"message":"NotImplementedError(\'Method not implemented exception\')","errorCode":"UNKNOWN"}', 'ERR_ACTOR_INVOKE_METHOD')
```

Expected behavior should have exception details like the method name which throws the exception, line number where the exception has been thrown and unique ID to match exceptions both on caller as well as callee side.
