### ISSUE TITLE
[Bug] `tox -e examples` fails to run successfully

### ISSUE THREAD

**Issue by dasanind** [dapr/python-sdk#604] opened 2023-09-22 19:24 UTC
## Expected Behavior

User is unable to run the `tox -e examples` successfully as mentioned in the [README.md
](https://github.com/dapr/python-sdk/blob/master/README.md)

## Actual Behavior

Here is the error: 
```
time="2023-09-22T15:10:45.304677-04:00" level=warning msg="failed to read from bindings: app channel not initialized " app_id=invoke-caller instance=Aninditas-MacBook-Pro.local scope=dapr.runtime type=log ver=1.11.3
                time="2023-09-22T15:10:45.304682-04:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 96ms" app_id=invoke-caller instance=Aninditas-MacBook-Pro.local scope=dapr.runtime type=log ver=1.11.3
                ℹ️  Checking if Dapr sidecar is listening on GRPC port 49403
                ℹ️  Dapr sidecar is up and running.
                ℹ️  Updating metadata for appPID: 99902
                ℹ️  Updating metadata for app command: python3 invoke-caller.py
                ✅  You're up and running! Both Dapr and your app logs will appear here.
                
                == APP == Traceback (most recent call last):
                == APP ==   File "/Users/aninditadas/Documents/Personal/MyLearning/Open-Source-Day/2023/SourceCode/python-sdk/examples/invoke-simple/invoke-caller.py", line 14, in <module>
                == APP ==     resp = d.invoke_method(
                == APP ==            ^^^^^^^^^^^^^^^^
                == APP ==   File "/Users/aninditadas/Documents/Personal/MyLearning/Open-Source-Day/2023/SourceCode/python-sdk/dapr/clients/__init__.py", line 116, in invoke_method
                == APP ==     return self.invocation_client.invoke_method(
                == APP ==            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                == APP ==   File "/Users/aninditadas/Documents/Personal/MyLearning/Open-Source-Day/2023/SourceCode/python-sdk/dapr/clients/http/dapr_invocation_http_client.py", line 162, in invoke_method
                == APP ==     return loop.run_until_complete(awaitable)
                == APP ==            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                == APP ==   File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
                == APP ==     return future.result()
                == APP ==            ^^^^^^^^^^^^^^^
                == APP ==   File "/Users/aninditadas/Documents/Personal/MyLearning/Open-Source-Day/2023/SourceCode/python-sdk/dapr/clients/http/dapr_invocation_http_client.py", line 118, in invoke_method_async
                == APP ==     return await make_request()
                == APP ==            ^^^^^^^^^^^^^^^^^^^^
                == APP ==   File "/Users/aninditadas/Documents/Personal/MyLearning/Open-Source-Day/2023/SourceCode/python-sdk/dapr/clients/http/dapr_invocation_http_client.py", line 102, in make_request
                == APP ==     resp_body, r = await self._client.send_bytes(
                == APP ==                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                == APP ==   File "/Users/aninditadas/Documents/Personal/MyLearning/Open-Source-Day/2023/SourceCode/python-sdk/dapr/clients/http/client.py", line 99, in send_bytes
                == APP ==     raise (await self.convert_to_error(r))
                == APP == dapr.clients.exceptions.DaprInternalError: ("fail to invoke, id: invoke-receiver, err: couldn't find service: invoke-receiver", 'ERR_DIRECT_INVOKE')
                ℹ️  
                terminated signal received: shutting down
                ✅  Exited Dapr successfully
                
        ERROR expected lines not found:
                == APP == text/plain
                == APP == INVOKE_RECEIVED
                == APP == text/plain
                == APP == INVOKE_RECEIVED
        Expected stderr (output_match_mode: exact, match_order: sequential):
        Actual stderr:
                ❌  The App process exited with error code: exit status 1
                ❌  Error exiting App: exit status 1
                
Step: Shutdown dapr
        command: `dapr stop --app-id invoke-caller
dapr stop --app-id invoke-receiver`
        return_code: 0
        duration_seconds: 0.342
        Expected stdout (output_match_mode: exact, match_order: sequential):
                ✅  app stopped successfully: invoke-caller
                ✅  app stopped successfully: invoke-receiver
        Actual stdout:
                ✅  app stopped successfully: invoke-receiver
                
        ERROR expected lines not found:
                ✅  app stopped successfully: invoke-caller
        Expected stderr (output_match_mode: exact, match_order: sequential):
        Actual stderr:
                ❌  failed to stop app id invoke-caller: couldn't find app id invoke-caller
                

External link validation:
        https://docs.dapr.io/getting-started Status: 200
        https://www.python.org/downloads/ Status: 200

examples: exit 1 (12.37 seconds) /Users/aninditadas/Documents/Personal/MyLearning/Open-Source-Day/2023/SourceCode/python-sdk/examples> ./validate.sh invoke-simple pid=99872
  examples: FAIL code 1 (57.53=setup[0.05]+cmd[1.17,1.01,1.00,1.00,5.40,19.78,4.83,6.51,4.41,12.37] seconds)
  evaluation failed :( (57.58 seconds)


```

## Steps to Reproduce the Problem

Run `tox -e examples` as mentioned in the [README.md
](https://github.com/dapr/python-sdk/blob/master/README.md)

## Release Note

RELEASE NOTE:

**Comment by sicoyle** [comment] 2023-09-22 22:02
@dasanind Hiiii! Hope you are enjoying the Grace Hopper Conference Open Source day! Do you need help with this?

**Comment by berndverst** [comment] 2023-10-02 19:40
Thanks for filing this issue. This is actually expected behavior due to ongoing Dapr 1.12 release activities. Please install Dapr 1.12-rc.5 (`dapr uninstall`, `dapr init --runtime-version 1.12.0-rc.5`) and try again.

We have merged changes into the master branch which only will work with dapr 1.12. So you must install one of the Dapr 1.12 release candidates. Alternatively, if you wish to use Dapr 1.11.X you can check out the `release-1.10` branch (which track Dapr Runtime 1.11) branch and run the command against that branch.

This is actually running successfully in CI/CD which downloads the latest 1.12 RC. See this workflow run: https://github.com/dapr/python-sdk/actions/runs/6358539125

The `validate-examples` workflow in CI/CD runs `tox -e examples` against Dapr 1.12-rc.5 right now.

**Closed by berndverst** 2023-10-02 19:40 UTC
Labels: kind/bug
